### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by pamm01** [soderlundf/telldus#1]
This happens:

/tmp/telldus/telldus-core-2.1.2# make
Scanning dependencies of target TelldusCommon
[  1%] Building CXX object common/CMakeFiles/TelldusCommon.dir/Event.cpp.o
[  3%] Building CXX object common/CMakeFiles/TelldusCommon.dir/Message.cpp.o
[  5%] Building CXX object common/CMakeFiles/TelldusCommon.dir/Mutex.cpp.o
[  7%] Building CXX object common/CMakeFiles/TelldusCommon.dir/Strings.cpp.o
[  8%] Building CXX object common/CMakeFiles/TelldusCommon.dir/Thread.cpp.o
[ 10%] Building CXX object common/CMakeFiles/TelldusCommon.dir/Event_unix.cpp.o
[ 12%] Building CXX object common/CMakeFiles/TelldusCommon.dir/EventHandler_unix.cpp.o
/tmp/telldus/telldus-core-2.1.2/common/EventHandler_unix.cpp: In member function ‘bool TelldusCore::EventHandler::waitForAny()’:
/tmp/telldus/telldus-core-2.1.2/common/EventHandler_unix.cpp:83:35: warning: narrowing conversion of ‘(((uint64_t)now.timeval::tv_sec) + (abstime_ns_large / 1000000000))’ from ‘uint64_t {aka long long unsigned int}’ to ‘__time_t {aka long int}’ inside { } [-Wnarrowing]
   timespec abstime = { now.tv_sec + (abstime_ns_large / 1000000000), abstime_ns_large % 1000000000 };
                        ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/telldus/telldus-core-2.1.2/common/EventHandler_unix.cpp:83:87: warning: narrowing conversion of ‘(abstime_ns_large % 1000000000)’ from ‘uint64_t {aka long long unsigned int}’ to ‘__syscall_slong_t {aka long int}’ inside { } [-Wnarrowing]
  = { now.tv_sec + (abstime_ns_large / 1000000000), abstime_ns_large % 1000000000 };
                                                    ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
[ 14%] Building CXX object common/CMakeFiles/TelldusCommon.dir/Socket_unix.cpp.o
[ 16%] Linking CXX static library libTelldusCommon.a
[ 16%] Built target TelldusCommon
Scanning dependencies of target telldusd
[ 17%] Building CXX object service/CMakeFiles/telldusd.dir/ClientCommunicationHandler.cpp.o
[ 19%] Building CXX object service/CMakeFiles/telldusd.dir/Controller.cpp.o
[ 21%] Building CXX object service/CMakeFiles/telldusd.dir/ControllerManager.cpp.o
[ 23%] Building CXX object service/CMakeFiles/telldusd.dir/ControllerMessage.cpp.o
[ 25%] Building CXX object service/CMakeFiles/telldusd.dir/Device.cpp.o
[ 26%] Building CXX object service/CMakeFiles/telldusd.dir/DeviceManager.cpp.o
/tmp/telldus/telldus-core-2.1.2/service/DeviceManager.cpp: In member function ‘void DeviceManager::executeActionEvent()’:
/tmp/telldus/telldus-core-2.1.2/service/DeviceManager.cpp:77:7: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
  std::auto_ptr<TelldusCore::MutexLocker> deviceLocker(0);
       ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /usr/include/c++/7/tr1/memory:39,
                 from /tmp/telldus/telldus-core-2.1.2/common/Event.h:12,
                 from /tmp/telldus/telldus-core-2.1.2/service/Controller.h:11,
                 from /tmp/telldus/telldus-core-2.1.2/service/Device.h:12,
                 from /tmp/telldus/telldus-core-2.1.2/service/DeviceManager.h:1 ,
                 from /tmp/telldus/telldus-core-2.1.2/service/DeviceManager.cpp:7:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/tmp/telldus/telldus-core-2.1.2/service/DeviceManager.cpp:87:23: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   deviceLocker = std::auto_ptr<TelldusCore::MutexLocker>(new TelldusCore::MutexLocker(it->second));
                       ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /usr/include/c++/7/tr1/memory:39,
                 from /tmp/telldus/telldus-core-2.1.2/common/Event.h:12,
                 from /tmp/telldus/telldus-core-2.1.2/service/Controller.h:11,
                 from /tmp/telldus/telldus-core-2.1.2/service/Device.h:12,
                 from /tmp/telldus/telldus-core-2.1.2/service/DeviceManager.h:1 ,
                 from /tmp/telldus/telldus-core-2.1.2/service/DeviceManager.cpp:7:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 28%] Building CXX object service/CMakeFiles/telldusd.dir/Log.cpp.o
[ 30%] Building CXX object service/CMakeFiles/telldusd.dir/Sensor.cpp.o
[ 32%] Building CXX object service/CMakeFiles/telldusd.dir/Settings.cpp.o
[ 33%] Building CXX object service/CMakeFiles/telldusd.dir/TelldusMain.cpp.o
[ 35%] Building CXX object service/CMakeFiles/telldusd.dir/TellStick.cpp.o
[ 37%] Building CXX object service/CMakeFiles/telldusd.dir/Timer.cpp.o
[ 39%] Building CXX object service/CMakeFiles/telldusd.dir/EventUpdateManager.cpp.o
[ 41%] Building CXX object service/CMakeFiles/telldusd.dir/ConnectionListener_unix.cpp.o
[ 42%] Building CXX object service/CMakeFiles/telldusd.dir/main_unix.cpp.o
[ 44%] Building CXX object service/CMakeFiles/telldusd.dir/SettingsConfuse.cpp.o
[ 46%] Building CXX object service/CMakeFiles/telldusd.dir/TellStick_libftdi.cpp.o
[ 48%] Building CXX object service/CMakeFiles/telldusd.dir/Protocol.cpp.o
[ 50%] Building CXX object service/CMakeFiles/telldusd.dir/ProtocolBrateck.cpp.o
[ 51%] Building CXX object service/CMakeFiles/telldusd.dir/ProtocolComen.cpp.o
[ 53%] Building CXX object service/CMakeFiles/telldusd.dir/ProtocolEverflourish.cpp.o
[ 55%] Building CXX object service/CMakeFiles/telldusd.dir/ProtocolFineoffset.cpp.o
[ 57%] Building CXX object service/CMakeFiles/telldusd.dir/ProtocolFuhaote.cpp.o
[ 58%] Building CXX object service/CMakeFiles/telldusd.dir/ProtocolGroup.cpp.o
[ 60%] Building CXX object service/CMakeFiles/telldusd.dir/ProtocolHasta.cpp.o
[ 62%] Building CXX object service/CMakeFiles/telldusd.dir/ProtocolIkea.cpp.o
/tmp/telldus/telldus-core-2.1.2/service/ProtocolIkea.cpp: In member function ‘virtual std::__cxx11::string ProtocolIkea::getStringForMethod(int, unsigned char, Controller*)’:
/tmp/telldus/telldus-core-2.1.2/service/ProtocolIkea.cpp:26:27: error: narrowing conversion of ‘170’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
  const char B0[] = {170, 0};
                           ^
service/CMakeFiles/telldusd.dir/build.make:662: recipe for target 'service/CMakeFiles/telldusd.dir/ProtocolIkea.cpp.o' failed
make[2]: *** [service/CMakeFiles/telldusd.dir/ProtocolIkea.cpp.o] Error 1
CMakeFiles/Makefile2:140: recipe for target 'service/CMakeFiles/telldusd.dir/all' failed
make[1]: *** [service/CMakeFiles/telldusd.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

I'm using a x86 computer, maybe thats the problem?

**Comment by vsurlien** [comment]
I have the same problem. I am running : 
Ubuntu Linux 18.04.1 amd64.

Is it possible to remove the ProtocolIkea and will it help? I dont use the Ikea part in my house.

**Comment by dr-eamy** [comment]
I got it to work whit http://download.telldus.com/pool/main/t/telldus-core/telldus-core_2.1.3-beta1.orig.tar.gz

**Comment by vsurlien** [comment]
I was able to comile the telldus core 2.1.2 with adding these lines at the end of CMakeLists.txt in step 3.

`SET(FORCE_COMPILE_FROM_TRUNK TRUE)
SET(GCC_COVERAGE_COMPILE_FLAGS "-Wno-narrowing")
SET(GCC_COVERAGE_LINK_FLAGS "-pthread -lpthread")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${GCC_COVERAGE_COMPILE_FLAGS}")
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${GCC_COVERAGE_LINK_FLAGS}")`

I found this in this [forum](https://forum.telldus.com/viewtopic.php?f=15&t=6201&sid=2958e789288f7d971a7515a474875c7f#p34307).

The program is running now, but not tested with tellstick yet.

**Comment by GummansGubbe** [comment]
The narrowing error is related to step 4 in soderlundf's readme.
Also, do both step 6 and 7 before 8. I jumped the gun there...




Step 4 - Add a compilation flag
Edit CMakeLists.txt and add (at the top of the file):
set(CMAKE_CXX_FLAGS "-std=c++98")

Step 5 - Run cmake
cmake .

Step 6 - Add -pthread for tdtool
Edit tdtool/CMakeFiles/tdtool.dir/link.txt and at the end of the line, add
-pthread

Step 7 - Add -pthread for tdadmin
Edit tdadmin/CMakeFiles/tdadmin.dir/link.txt and att the end of the line, add
-pthread

Step 8 - Run make
make

Step 9 - Install
make install

**Comment by vsurlien** [comment]
> The narrowing error is related to step 4 in soderlundf's readme.
> Also, do both step 6 and 7 before 8. I jumped the gun there...

What hardware did are you running pamm01? I tried to compile on a RPi with only using soderlundf's readme. It compiled just fine. But it did not work when i tried on my amd64 computer.
I ended up with using soderlundf's readme and only changed to only exchanging  the  telldus core version to dr-eamy's telldus-core_2.1.3-beta1.orig.tar.gz. No need for the extra lines that I suggested in my previous comment

**Comment by pamm01** [comment]
I'm using a x86 thin client.

**Comment by soderlundf** [comment]
Sorry for late reply. Stuck in life and such. Is this still an issue or can I close it as solved?

**Comment by soderlundf** [comment]
Since pamm01 reported it to work I'm going to be allmighty and close this issue.
