### ISSUE TITLE
Debian 9

### ISSUE THREAD

**Issue by BernadoEco** [soderlundf/telldus#2]
I have a supplement:

**telldus-core-2.1.2**

Step 1: 
apt-get install build-essential libftdi1 libftdi-dev libconfuse-common libconfuse-dev libconfuse1 cmake pkg-config 

and:

apt install doxygen

Step3:
not do it

Step 2:
Are the same as in their description

and:

wget https://raw.githubusercontent.com/telldus/telldus/master/telldus-core/Doxyfile.in

Step 4 - Step 9: 
Are the same as in their description!

Step 10:

ln -s /usr/local/lib/libtelldus-core.so.2 /usr/bin

#############################################################################

telldus-2.1.3-beta1
http://download.telldus.com/pool/main/t/telldus-core/telldus-core_2.1.3-beta1.orig.tar.gz

Step 1: 
apt-get install build-essential libftdi1 libftdi-dev libconfuse-common libconfuse-dev libconfuse1 cmake pkg-config 

and:

apt install doxygen

Step 2:
Are the same as in their description

and:

wget https://raw.githubusercontent.com/telldus/telldus/master/telldus-core/Doxyfile.in

Step 3 - 4:
not do it

Step 5:
Are the same as in their description

Step 6 -7:
not do it

Step 8-9:
Are the same as in their description

Step 10:

ln -s /usr/local/lib/libtelldus-core.so.2 /usr/bin

##########################################################################

Last Step Create init.d-Skript /etc/init.d/telldusd:

https://github.com/ktoso/go-home-raspberry/blob/master/ops/telldusd

**Comment by GummansGubbe** [comment]
my@my:~$ more /lib/systemd/system/telldusd.service
[Unit]
Description=Tellstick service daemon
After=multi-user.target

[Service]
Type=forking
ExecStart=/usr/local/sbin/telldusd

[Install]
WantedBy=multi-user.target


2018-12-01 19:22 GMT+01:00, BernadoEco <notifications@github.com>:

**Comment by soderlundf** [comment]
Thanks BernadoEco and GummansGubbe for your additions. I'm going to be allmighty and close this issue.
